[build]
  publish = "app/out"
  command = "cd app && npm run build"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 